### ISSUE TITLE
Does this have the ability to POST to an API?

### ISSUE THREAD

**Issue by cbarratt** [gabrielcsapo/places#56]
Hey, I came here from GPS-Logger-IOS and this app also looks super cool. I'm developing an API backend service to accept the data and store it in a database to create a web UI that can also display the tracking data

**Comment by gabrielcsapo** [comment]
@cbaratt you could override the save function to post the data to an API. I am pretty sure everything I persist data I call save.

**Comment by gabrielcsapo** [comment]
@cbaratt let me know if you need any help! 😊Any code cleanup / feature PRS are welcome!
